from jchess.geometry import Vector as Vector, VectorLike as VectorLike

class DisplayArray:
    rows: list[list[str]]

    def __init__(self, string: str) -> None: ...
    @property
    def n_rows(self) -> int: ...
    @property
    def n_cols(self) -> int: ...
    def __getitem__(self, position: VectorLike) -> str: ...
    def __setitem__(self, position: VectorLike, value: str) -> None: ...
    def merge_in(self, other: DisplayArray, *, anchor: str) -> None: ...

INVALID_INPUT_MSG: str
