from typing import Any, Iterator

class Vector:
    x: int
    y: int
    def __init__(self, x: int, y: int) -> None: ...
    def __getitem__(self, index: int) -> int: ...
    def __add__(self, other: Vector | tuple[int, int]) -> Vector: ...
    def __sub__(self, other: Vector | tuple[int, int]) -> Vector: ...
    def __eq__(self, other: Any) -> bool: ...
    def __iter__(self) -> Iterator[int]: ...
    def __len__(self) -> int: ...
