[build-requires]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "clichess"
version = "0.0.1"
authors = [
    { name="j-hil", email="92876062+j-hil@users.noreply.github.com" },
]
description = "A package to allow chess in the command line!"
requires-python = ">=3.10"
readme = "README.md"
license = { file="LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3",
    "Operating System :: OS Independent",
    "Development Status :: 1 - Planning"
]

[project.urls]
"Homepage" = "https://j-hil@github.com/j-hil/cli-chess.git"

